### ISSUE TITLE
Problem with httpClient injection

### ISSUE THREAD

**Issue by gnihi** [hzub/angular-6-with-babel-typescript#2]
Thank you for the boilerplate. 
I've tried to get my project transpiled with babel and used your config. But I can't figure out how to use dependency injection. 
You can recreate the problem if you inject the httpClient into your app.component.ts.
Am I missing some plugin or anything else? 

```import { Component } from '@angular/core';
import {HttpClient} from '@angular/common/http';

@Component({
  selector: 'app-root',
  template: `
    <div>
      <h1>{{title}}</h1>
      <div>The number: {{x}}</div>
    </div>
  `,
})
export class AppComponent {
  title: string = 'Working component!';
  x: number = 123;

  constructor(private http: HttpClient){

  }
}
```

**Comment by hzub** [comment]
Hi!
That one can be tricky, since without "real" TS our Angular app won't have any idea of which injectable it should deal with. Please refer to https://blog.thoughtram.io/angular/2015/05/09/writing-angular-2-code-in-es5.html - using explicit DI with angular.Core.Inject should do the trick. It's still not so convenient but hey, whole thing with preset-typescript is just an experiment ;)

**Comment by gnihi** [comment]
I will give it a try.
Thanks for the reponse :)
